name = "affiliate-plus-tracker"
main = "worker.js"
compatibility_date = "2026-09-30"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "affiliate-plus-tracker"
database_id = "5d1a9042-438f-4075-979e-b48055d30651"

[vars]
PUBLIC_BASE_URL = "https://affiliate-plus-tracker.lospoppos-twitch.workers.dev"
